spring.application.name=auth-service
server.port=8081
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mss_auth}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jackson.serialization.write-dates-as-timestamps=false
app.portal-url=${APP_PORTAL_URL:http://localhost:3000}
security.mail.from=${SECURITY_MAIL_FROM:${SPRING_MAIL_USERNAME:no-reply@skyline.local}}
